/**
 * The setup wizard and its saved answers.
 *
 * Answers persist to `.env.gopilot` in ordinary dotenv format, using the same
 * variable names documented in `.env.example` -- RESEARCH_MODE already *is* the
 * mode, so there is no parallel config system to keep in sync. The file is
 * gitignored, which is what makes it safe to hold an optional API key.
 *
 * Demo mode deliberately writes almost nothing: the zero-config path works
 * because every setting already has a working default, and the CLI must not
 * quietly become a prerequisite for it.
 */

import { createInterface } from "node:readline/promises";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stdin, stdout } from "node:process";

export const CONFIG_FILE = ".env.gopilot";

export const MODES = {
  demo: {
    key: "demo",
    label: "Demo",
    blurb: "fixture data, nothing external, no keys",
    researchMode: "fixture",
    script: "dev",
  },
  live: {
    key: "live",
    label: "Live research",
    blurb: "fetches real company websites (needs Postgres + Redis already running)",
    researchMode: "live",
    script: "dev:live",
  },
  docker: {
    key: "docker",
    label: "Live research + Docker",
    blurb: "same, and this CLI starts Postgres + Redis for you",
    researchMode: "live",
    script: "dev:live",
    docker: true,
  },
};

export function configPath(root) {
  return join(root, CONFIG_FILE);
}

export function readConfig(root) {
  const file = configPath(root);
  if (!existsSync(file)) return null;
  const env = {};
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index === -1) continue;
    env[trimmed.slice(0, index).trim()] = trimmed.slice(index + 1).trim();
  }
  if (!env.RESEARCH_MODE) return null;
  const mode =
    env.RESEARCH_MODE === "live"
      ? env.GOPILOT_DOCKER_INFRA === "true"
        ? MODES.docker
        : MODES.live
      : MODES.demo;
  return { mode, env };
}

export function writeConfig(root, mode, extras = {}) {
  const lines = [
    "# Generated by `npx gopilot`. Safe to edit, delete, or commit-ignore.",
    "# Variable names match .env.example; this file simply records your answers.",
    "# Gitignored, so an API key placed here does not reach the repository.",
    "",
    `RESEARCH_MODE=${mode.researchMode}`,
  ];
  if (mode.docker) lines.push("GOPILOT_DOCKER_INFRA=true");
  const keys = Object.entries(extras).filter(([, value]) => value);
  if (keys.length) {
    lines.push(
      "",
      "# Optional. BYOA -- importing your own accounts -- never needs these;",
      "# they only enable the experimental discovery workflow.",
    );
    for (const [name, value] of keys) lines.push(`${name}=${value}`);
  }
  writeFileSync(configPath(root), `${lines.join("\n")}\n`, "utf8");
}

/** True when we can actually ask a human something. */
export function interactive() {
  return Boolean(stdin.isTTY && stdout.isTTY);
}

export async function runWizard({ docker }) {
  const available = [MODES.demo, MODES.live];
  if (docker.available) available.push(MODES.docker);

  const rl = createInterface({ input: stdin, output: stdout });

  // Once stdin ends, readline stops cooperating in two different ways: a
  // pending question never settles, and any *later* question throws
  // ERR_USE_AFTER_CLOSE. Both have to be handled, or the CLI either hangs or
  // dies with a stack trace instead of falling back to a sane default. The
  // isTTY guard makes this unreachable in normal use; it showed up under
  // piped input during testing, which is exactly what testing is for.
  let ended = false;
  rl.once("close", () => {
    ended = true;
  });
  const ask = async (prompt, fallback = "") => {
    if (ended) return fallback;
    try {
      return await Promise.race([
        rl.question(prompt),
        new Promise((resolve) => rl.once("close", () => resolve(fallback))),
      ]);
    } catch {
      return fallback;
    }
  };

  try {
    console.log("Which mode should GoPilot start in?\n");
    available.forEach((mode, index) => {
      const marker = index === 0 ? " (default)" : "";
      console.log(`  ${index + 1}. ${mode.label}${marker}`);
      console.log(`     ${mode.blurb}`);
    });
    if (!docker.available) {
      console.log(
        docker.installed
          ? "\n  (Docker is installed but its daemon is not responding, so the\n   Docker option is hidden. Start Docker Desktop and re-run to see it.)"
          : "\n  (No Docker detected, so the Docker option is hidden.)",
      );
    }

    const answer = (await ask(`\nChoice [1-${available.length}]: `)).trim();
    const picked = available[Number(answer) - 1] ?? available[0];

    const extras = {};
    if (picked !== MODES.demo) {
      console.log(
        "\nOptional: Exa / Tavily API keys enable the experimental discovery",
        "\nworkflow. The core BYOA loop -- import your own accounts and research",
        "\nthem against their own websites -- does not need them at all.",
      );
      const wants = (await ask("\nAdd search-provider keys now? [y/N]: "))
        .trim()
        .toLowerCase();
      if (wants === "y" || wants === "yes") {
        extras.EXA_API_KEY = (await ask("EXA_API_KEY (blank to skip): ")).trim();
        extras.TAVILY_API_KEY = (
          await ask("TAVILY_API_KEY (blank to skip): ")
        ).trim();
      }
    }

    console.log(`\nStarting in ${picked.label} mode.`);
    await ask("Press Enter to continue, or Ctrl+C to abort: ");
    return { mode: picked, extras };
  } finally {
    rl.close();
  }
}
